### ISSUE TITLE
Consider moving the grammar(s) to `tree-sitter-grammars`

### ISSUE THREAD

**Issue by amaanq** [Philipp-M/tree-sitter-yuck#8]
Hey @Philipp-M, I hope you've been well. We at nvim-treesitter (and potentially more folks from other teams interested in an ecosystem-wide effort to maintain grammars) have decided to move all of our own grammars collectively into one org, to make it easier for us all to fix bugs or keep things up to date (scanner crashes, regenerating with the latest abi, etc.) without having to rely on one sole maintainer (you).

This is 100% optional, and please don't feel pressured or feel like you have an obligation of moving the grammar to the org, but it will help everyone a lot, us at nvim-treesitter, other users downstream, to know that a grammar won't ever die should a maintainer call it quits or go MIA. We also have org-wide actions that we maintain (out of sight, out of mind for you) and a grammar template (soon for newbies) in place to ensure authors have a better experience with working on and fixing tree-sitter grammars. It also enables anyone looking to find grammars for a specific language to only have to search in one spot

Our org is here: https://github.com/tree-sitter-grammars

Something you might find of interest is that the ecosystem is moving towards adopting last-wins query precedence (iirc Helix is going to switch, Zed currently uses the neovim model, some others as well and soon upstream will kill first-wins), and sharing a common set of query captures and predicate names (getting there).

If you want to participate (and don't worry, you'll still have full write perms to your repo, just no admin access), that'd be great! All you have to do is transfer the repo to me in the repository settings and I'll handle it from there. Thanks a lot, and again no worries if the answer is no! Also, it'd be cool to get ungrammar as well in the org if you're on board :grin:

**Comment by Philipp-M** [comment]
Sure, happy to do that (including the ungrammar repo). An organization to manage all of these with unified and combined effort makes sense.

**Comment by amaanq** [comment]
Nice! It's something I've wanted for a while because the state of different grammar repos varies too much in terms of quality and maintenance status, and we want to have a hub where grammars will be of good quality for any users.

Do you mind transferring the repos to me first (which is done in the repo settings)? Then I can transfer them to the org and you'll have write access to both

**Comment by amaanq** [comment]
Oops, I was just reminded you can't transfer them if I already have that repo name (from my fork), I've just deleted those so it should be ok now

**Comment by Philipp-M** [comment]
I can do that, but why the indirection? Can I not directly transfer it to the organization?

**Comment by amaanq** [comment]
No unless you have admin rights (I think)

**Comment by Philipp-M** [comment]
Shouldn't be necessary AFAIK:

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by amaanq** [comment]
But you can't create a repo in `tree-sitter-grammars`, and I can, hence the indirection, but maybe I'm missing something

**Comment by clason** [comment]
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

Yes, but _you_ don't have that permission, and _we_ don't have the permission to initiate a transfer (only repo owners have that, not maintainers). So the only two choices are
1. you add an org owner as owner here; or
2. you transfer to an org owner's personal account (which is handled differently via an email asking for acceptance -- since a personal account has a single point of contact).

**Comment by Philipp-M** [comment]
To be clear, I don't have an issue transferring it temporarily to an org owner/member that has this permission (and then gain repo role admin access in the repo in the org?).
 

I'm just interested in the general organization governance. It makes sense to me that maintainers of repos in that org have the permission to create new repos there (i.e. are members of that org) and generally have more permissions (to e.g. approve PRs of other grammars etc.) as this seems to be a community effort to put all kinds of tree-sitter-grammar repos under one umbrella?

> you add an org owner as owner here

AFAIK that isn't possible with personal repos. That only works in organizations.

**Comment by clason** [comment]
> I'm just interested in the general organization governance. It makes sense to me that maintainers of repos in that org have the permission to create new repos there (i.e. are members of that org) and generally have more permissions (to e.g. approve PRs of other grammars etc.) as this seems to be a community effort to put all kinds of tree-sitter-grammar repos under one umbrella?

Makes sense. That is not planned currently; it's not a "all for one and one for all"; the org members are more concerned with tooling, automation, and upstream coordination.

**Comment by ObserverOfTime** [comment]
We can't exactly allow any person to do anything they want with any of the parsers for obvious reasons…

**Comment by Philipp-M** [comment]
Well it's not exactly any person, it would be the maintainers of tree-sitter grammars there (IMO). They can't do anything they want. There could/would still be a lot of restrictions (especially security-wise). I'm in organizations that are quite open, with e.g. requiring one approved review to merge from any member in there (so it's not possible without some feedback from another person in there to modify code). It works quite well (no incident so far), and IMO would make sense for such community maintenance effort (as the parsers are similar across the board, so domain knowledge is existing for each of the maintainers).

But hey, I don't plan to do much tree-sitter stuff currently, it doesn't really affect me, just some input/food for thought.

**Comment by clason** [comment]
Sure. As I wrote, that is a reasonable suggestion. We just have different plans right now while setting up; this may change later when things are running smoothly.

If you prefer to keep the parser under your own control, that's totally understandable and fine, too. It's just an offer. (Not like we are trying to Pokemon this thing ;))

**Comment by Philipp-M** [comment]
I just started the transfer to @amaanq
Hadn't had the time till now

**Comment by amaanq** [comment]
Thanks a lot!! :grin: They're at https://github.com/tree-sitter-grammars/tree-sitter-ungrammar and https://github.com/tree-sitter-grammars/tree-sitter-yuck now, you should also still have write access, lmk if not
